apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: maxain27/alpha-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URL
              value: "mongodb://database:27017"
            - name: DB_NAME
              value: "streamflix_db"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800
  selector:
    app: backend
