export const languages = [
  { code: "en", label: "English" },
  { code: "es", label: "Español" },
  { code: "hi", label: "हिंदी" },
  { code: "fr", label: "Français" },
  { code: "de", label: "Deutsch" },
];

export const translations = {
  en: {
    signIn: "Sign In",
    emailPlaceholder: "Email or phone number",
    passwordPlaceholder: "Password",
    emailError: "Please enter a valid email or phone number.",
    passwordError: "Your password must contain between 4 and 60 characters.",
    signingIn: "Signing In...",
    or: "OR",
    useSignInCode: "Use a Sign-In Code",
    forgotPassword: "Forgot password?",
    rememberMe: "Remember me",
    newHere: "New to Alpha?",
    signUpNow: "Sign up now.",
    recaptchaNotice: "This page is protected by Google reCAPTCHA to ensure you're not a bot.",
    learnMore: "Learn more.",
    questionsCall: "Questions? Call",
    incorrectPasswordMsg: "Incorrect password for {email}. You can use a sign-in code, reset your password or try again.",
    signInSuccess: "Sign in successful! (Demo)",
    footerLinks: [
      "FAQ",
      "Help Center",
      "Terms of Use",
      "Privacy",
      "Cookie Preferences",
      "Corporate Information",
    ],
  },
  es: {
    signIn: "Iniciar sesión",
    emailPlaceholder: "Email o número de teléfono",
    passwordPlaceholder: "Contraseña",
    emailError: "Escribe un email o un número de teléfono válido.",
    passwordError: "La contraseña debe tener entre 4 y 60 caracteres.",
    signingIn: "Iniciando sesión...",
    or: "O",
    useSignInCode: "Usar un código de inicio de sesión",
    forgotPassword: "¿Olvidaste tu contraseña?",
    rememberMe: "Recuérdame",
    newHere: "¿Primera vez en Alpha?",
    signUpNow: "Suscríbete ahora.",
    recaptchaNotice: "Esta página está protegida por Google reCAPTCHA para garantizar que no eres un bot.",
    learnMore: "Más información.",
    questionsCall: "¿Preguntas? Llama al",
    incorrectPasswordMsg: "Contraseña incorrecta para {email}. Puedes usar un código de inicio de sesión o intentar de nuevo.",
    signInSuccess: "¡Inicio de sesión exitoso! (Demo)",
    footerLinks: [
      "Preguntas frecuentes",
      "Centro de ayuda",
      "Términos de uso",
      "Privacidad",
      "Preferencias de cookies",
      "Información corporativa",
    ],
  },
  hi: {
    signIn: "साइन इन करें",
    emailPlaceholder: "ईमेल या फोन नंबर",
    passwordPlaceholder: "पासवर्ड",
    emailError: "कृपया एक वैध ईमेल या फोन नंबर दर्ज करें।",
    passwordError: "आपका पासवर्ड 4 से 60 अक्षरों के बीच होना चाहिए।",
    signingIn: "साइन इन हो रहा है...",
    or: "या",
    useSignInCode: "साइन-इन कोड का उपयोग करें",
    forgotPassword: "पासवर्ड भूल गए?",
    rememberMe: "मुझे याद रखें",
    newHere: "क्या आप अल्फा पर नए हैं?",
    signUpNow: "अभी साइन अप करें।",
    recaptchaNotice: "यह पृष्ठ Google reCAPTCHA द्वारा संरक्षित है ताकि यह सुनिश्चित किया जा सके कि आप बॉट नहीं हैं।",
    learnMore: "और जानें।",
    questionsCall: "कोई प्रश्न? कॉल करें",
    incorrectPasswordMsg: "{email} के लिए गलत पासवर्ड। आप साइन-इन कोड का उपयोग कर सकते हैं या फिर से प्रयास कर सकते हैं।",
    signInSuccess: "सफलतापूर्वक साइन इन किया गया! (डेमो)",
    footerLinks: [
      "सामान्य प्रश्न",
      "सहायता केंद्र",
      "उपयोग की शर्तें",
      "गोपनीयता",
      "कुकी प्राथमिकताएं",
      "कॉर्पोरेट जानकारी",
    ],
  },
  fr: {
    signIn: "Se connecter",
    emailPlaceholder: "E-mail ou numéro de téléphone",
    passwordPlaceholder: "Mot de passe",
    emailError: "Veuillez saisir une adresse e-mail ou un numéro de téléphone valide.",
    passwordError: "Votre mot de passe doit contenir entre 4 et 60 caractères.",
    signingIn: "Connexion...",
    or: "OU",
    useSignInCode: "Utiliser un code de connexion",
    forgotPassword: "Mot de passe oublié ?",
    rememberMe: "Se souvenir de moi",
    newHere: "Nouveau sur Alpha ?",
    signUpNow: "S'inscrire maintenant.",
    recaptchaNotice: "Cette page est protégée par Google reCAPTCHA pour s'assurer que vous n'êtes pas un robot.",
    learnMore: "En savoir plus.",
    questionsCall: "Des questions ? Appelez le",
    incorrectPasswordMsg: "Mot de passe incorrect pour {email}. Vous pouvez utiliser un code de connexion ou réessayer.",
    signInSuccess: "Connexion réussie ! (Démo)",
    footerLinks: [
      "FAQ",
      "Centre d'aide",
      "Conditions d'utilisation",
      "Confidentialité",
      "Préférences de cookies",
      "Informations d'entreprise",
    ],
  },
  de: {
    signIn: "Anmelden",
    emailPlaceholder: "E-Mail-Adresse oder Telefonnummer",
    passwordPlaceholder: "Passwort",
    emailError: "Bitte geben Sie eine gültige E-Mail-Adresse oder Telefonnummer ein.",
    passwordError: "Ihr Passwort muss zwischen 4 und 60 Zeichen lang sein.",
    signingIn: "Wird angemeldet...",
    or: "ODER",
    useSignInCode: "Anmeldecode verwenden",
    forgotPassword: "Passwort vergessen?",
    rememberMe: "Angemeldet bleiben",
    newHere: "Neu bei Alpha?",
    signUpNow: "Jetzt registrieren.",
    recaptchaNotice: "Diese Seite ist durch Google reCAPTCHA geschützt, um sicherzustellen, dass Sie kein Bot sind.",
    learnMore: "Weitere Informationen.",
    questionsCall: "Fragen? Rufen Sie an:",
    incorrectPasswordMsg: "Falsches Passwort für {email}. Sie können einen Anmeldecode verwenden oder es erneut versuchen.",
    signInSuccess: "Erfolgreich angemeldet! (Demo)",
    footerLinks: [
      "FAQ",
      "Hilfe-Center",
      "Nutzungsbedingungen",
      "Datenschutz",
      "Cookie-Einstellungen",
      "Unternehmensinformationen",
    ],
  },
};

export const DEMO_CREDENTIALS = {
  email: "demo@alpha.com",
  password: "alpha123",
};